### ISSUE TITLE
Create user interaction use cases

### ISSUE THREAD

**Issue by andrewmagill** [identifier-services/IDservices_assessment#11]
Provide a couple scenarios describing likely user interaction with the site.  

For example: 
- user creates projects
- user registers fastq files, etc.

or
- user creates project
- user defines specimen
- user defines process
- ...

**Comment by ramonawalls** [comment]
@andrewmagill @mrhanlon : I added some user scenarios here (https://github.com/identifier-services/IDservices_assessment/wiki/Use-cases-for-development-team) based on our use cases.

**Comment by ramonawalls** [comment]
I refined the use cases slightly and added proposed dates. @andrewmagill @mrhanlon @mesteva We can discuss these on Monday's call.
