### ISSUE TITLE
MAIZE_file locations on Corral and SRA

### ISSUE THREAD

**Issue by mesteva** [identifier-services/IDservices_assessment#2]
[MAIZE_file_locations.xlsx](https://github.com/identifier-services/IDservices_assessment/files/15155/MAIZE_file_locations.xlsx)

**Comment by ramonawalls** [comment]
File locations as a text file here: https://github.com/identifier-services/IDservices_assessment/blob/master/docs/file_locations/MAIZE_WGBS_file_locations.txt
