### ISSUE TITLE
MAIZE_metadata

### ISSUE THREAD

**Issue by mesteva** [identifier-services/IDservices_assessment#3]
More detailed metadata than project metadata
[MAIZE_metadata.xlsx](https://github.com/identifier-services/IDservices_assessment/files/15157/MAIZE_metadata.xlsx)

**Comment by ramonawalls** [comment]
metadata file available here: https://github.com/identifier-services/IDservices_assessment/blob/master/docs/metadata_files/MAIZE_WGBS_metadata.xlsx
